---
title: "Solução Lista 01"
author: |
        | Nome: Vinicius de Oliveira Bezerra
        | E-mail: v.bezerra@aluno.ufabc.edu.br
        | Nome: Deyved Kevyn Alves Lima
        | E-mail: deyved.lima@aluno.ufabc.edu.br
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.align='center',
                      cache=TRUE,
                      out.width = "60%",
                      out.heigth = "60%",
                      warning=FALSE,
                      message=FALSE)
options(width =70)
```

## Solução Exercício 01

```{r}
A = matrix(c(12,-1,-5,0,-1,7,2,-1,-5,2,10,1,0,-1,1,3),nrow=4) 
b = c(1,2,3,4)
solve(A,b)
```

## Solução Exercício 02

```{r}
#Funcoes
matriz_positiva = function(M) {
  # Verifica se a matriz é quadrada
  if (nrow(M) != ncol(M)) {
    return('Matriz não quadrada')
  }
  
  # Verifica se a matriz é transposta
  if (!identical(M, t(M))) {
    return('Matriz não transposta')
  }
  
  # Obtem o tamanho da matriz
  tamanho = nrow(M)
  
  # Verifica o determinante das submatrizes
  for (i in 1:tamanho) {
    m_aux = M[1:i, 1:i, drop = FALSE]
    
    det_matriz = det(m_aux)
     
    if (det_matriz < 0) {
      return(FALSE)
    }
  }
  
  return(TRUE)
}
#Cria a matriz 'A'
A = matrix(c(12, -1, -5, 0, -1, 7, 2, -1, -5, 2, 10, 1, 0, -1, 1, 3), byrow = FALSE, nrow = 4)

#Chama a funcao 
matriz_positiva(A)
```

## Solução Exercício 03

```{r}
#Importar Bibliotecas
library(ggplot2)

#Gera o Intervalo
x <- seq(-2*pi, 2*pi, length.out = 100)

#Cria um data frame
df <- data.frame(
  x = x,
  seno = sin(x),      # Calcula o seno de x
  cosseno = cos(x)    # Calcula o cosseno de x
)

#Imprime o grafico gráfico 
ggplot(df, aes(x = x)) + 
  geom_line(aes(y = seno, color = "Seno")) +      
  geom_line(aes(y = cosseno, color = "Cosseno")) + 
  labs(title = "Ex3 - Gráfico Seno e Cosseno",    
       x = "x",                                  
       y = "Valor") +                         
  theme_minimal()  
```

## Solução Exercício 04

```{r}
#Importar Bibliotecas
library(ggplot2)

#Matriz simétrica 'A' aleatória
set.seed(1)
X <- matrix(runif(100,-1,1),nrow=10)
A <- t(X) %*% X


lambdas <- seq(0, 10, by = 0.1)
cond_numbers <- sapply(lambdas, function(l) kappa(A + l * diag(nrow(A))))

#Cria o data frame
df_cond <- data.frame(lambda = lambdas, cond = cond_numbers)

#Imprime o gráfico
ggplot(df_cond, aes(x = lambda, y = cond)) +
  geom_line(color = "blue") +
  labs(title = "Número de Condicionamento vs Lambda",
       x = "Lambda",
       y = "Número de Condicionamento") +
  theme_minimal()
```

